#sylius_admin_order_item_unit:
#    resource: |
#        alias: sylius.order_item_unit
#        section: admin
#        templates: "@SyliusAdmin\\Crud"
#        only: ['index']
#        grid: sylius_admin_order_item_unit
#        permission: true
#    type: sylius.resource
