sylius_mailer:
  sender:
    name: clutchkickclassics.co.za
    address: clutch.kick.classics@gmail.com
  emails:
    new_entry:
      subject: "Clutch Kick Entry"
      template: "Email/emails/new_entry.html.twig"