sylius_terms_and_conditions:
  path: /terms-and-conditions
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
      template: '@SyliusShop/TermsAndConditions/index.html.twig'


sylius_privacy_policy:
  path: /privacy-policy
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
      template: '@SyliusShop/PrivacyPolicy/index.html.twig'


sylius_the_car:
  path: /1928-Armstrong-Siddeley
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
      template: '@SyliusShop/TheCar/show.html.twig'
      

sylius_how_to_enter:
  path: /how-to-enter
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@SyliusShop/HowToEnter/index.html.twig'


sylius_fabrication:
  path: /fabrication
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@SyliusShop/Fabrication/index.html.twig'


sylius_checkout_process_payment:
  path: /process-payment/{order_id}
  methods: [POST, GET]
  controller: App\Controller\ShopController::processPaymentAction


sylius_checkout_entry_email:
  path: /entry-email
  methods: [POST, GET]
  controller: App\Controller\ShopController::viewEmailAction




