sylius_terms_and_conditions:
  path: /terms-and-conditions
  methods: [GET]
  controller: App\Controller\ShopController::termsAndConditionsAction

sylius_privacy_policy:
  path: /privacy-policy
  methods: [GET]
  controller: App\Controller\ShopController::privacyPolicyAction

sylius_the_car:
  path: /1928-Armstrong-Siddeley
  methods: [GET]
  controller: App\Controller\ShopController::theCarAction


