# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: false

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'


    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']


    app.command.create_admin:    
        class: App\Command\CreateAdminCommand
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@sylius.factory.admin_user"
          - "@monolog.logger"
        tags:
          - { name: 'console.command', command: 'app:create-admin'  }

    App\Service\OrderCompletionService:
        public: true
        arguments:
            - '@monolog.logger'
            - '@App\EmailManager\NewEntryEmailManager'
            - '@doctrine.orm.entity_manager'

    App\EmailManager\NewEntryEmailManager:
        public: true
        arguments: [ '@sylius.email_sender', '@sylius.availability_checker', '@sylius.repository.admin_user' ]


    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    app.sylius_payment:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [ App\Payum\SyliusPaymentGatewayFactory ]
        tags:
            - { name: payum.gateway_factory_builder, factory: sylius_payment }

    App\Form\Type\SyliusGatewayConfigurationType:
        tags:
            - { name: sylius.gateway_configuration_type, type: sylius_payment, label: 'Payfast Payment' }
            - { name: form.type }

    App\Payum\Action\CaptureAction:
        arguments:
            - '@sylius.http_client'
        tags:
            - { name: payum.action, factory: sylius_payment, alias: payum.action.capture }

