sylius_order_item_index:
  resource: |
    alias: app.order_item_unit
    section: admin
    redirect: index
    except: [create, update, delete]
    templates: "@SyliusAdmin\\Crud"
    grid: admin_order_item_unit
    vars:
      index:
        header: 'Competition Entries List'
  type: sylius.resource
